'use client';
import {apiURL,sitePath} from '@/lib/deployment';

import {useEffect,useState} from 'react';


import {ArrowUpRight,RefreshCw} from 'lucide-react';
import {sources,type Source} from '@/lib/sources';
import {readingLink,type CatalogueBook} from '@/lib/catalogue';
function Shelf({source,title,label}:{source:Source;title:string;label:string}){
 const [books,setBooks]=useState<CatalogueBook[]>([]);const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [fallback,setFallback]=useState(false);const [round,setRound]=useState(0);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');fetch(apiURL('/api/catalogue?source='+source),{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('书目载入失败，请重试。');return r.json() as Promise<{books:CatalogueBook[];fallback:boolean}>;}).then(data=>{setBooks(data.books);setFallback(data.fallback);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[source,round]);
 return <section className={'home-shelf '+source} aria-label={title}><div className="shelf-title"><div><span>{label}</span><h2>{title}</h2></div><button disabled={busy} onClick={()=>setRound(n=>n+1)}><RefreshCw size={15}/> 换一批</button></div>{error&&<p role="alert">{error}</p>}<div className="home-books" aria-busy={busy}>{books.length?books.map((book,i)=><a href={readingLink(book.url)} key={book.url} className="discovery-book"><div className="discovery-cover" style={{'--cover-hue':String((source==='aozora'?140:205)+i*13)} as React.CSSProperties}><span className="cover-source">{title}</span><strong lang="ja">{book.title}</strong><span className="cover-author" lang="ja">{book.author}</span></div><div className="discovery-meta"><h3 lang="ja">{book.title}</h3><p lang="ja">{book.author||'作者未署名'}</p><span className="book-description" lang="ja">{book.description}</span><span className="start-reading">开始阅读 <ArrowUpRight size={14}/></span></div></a>):Array.from({length:5},(_,i)=><div className="catalogue-placeholder" key={i} aria-label="正在载入书目"/> )}</div>{fallback&&<p className="catalogue-note">书源目录暂时无法连接，当前从已保存的书目中随机展示。</p>}</section>;
}
export default function Home(){const [url,setUrl]=useState('');const [error,setError]=useState('');return <main className="home-page" data-theme="paper"><header className="topbar"><a href={sitePath('/')} className="brand"><span className="brand-mark">青</span><strong>青空<span>阅读室</span></strong></a><span className="top-note">六个书源 · 一个阅读室</span></header><div className="home-content"><section className="home-intro"><div><div className="eyebrow">YOUR NEXT READ</div><h1>今天，读些什么？</h1><p>六个书源，各五本。遇见下一段故事。</p></div><form className="home-open" onSubmit={e=>{e.preventDefault();try{setError('');window.location.assign(readingLink(url));}catch(e){setError((e as Error).message);}}}><label htmlFor="open-book">已经有想读的作品？</label><div className="url-field"><input id="open-book" required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="粘贴作品、图书卡或章节链接"/><button aria-label="打开作品"><ArrowUpRight size={20}/></button></div><p className="hint">支持下方六个书源的作品链接，网络小说按章载入。</p>{error&&<p className="home-error" role="alert">{error}</p>}</form></section>{(Object.keys(sources) as Source[]).map(source=><Shelf key={source} source={source} title={sources[source].name} label={sources[source].label}/>)}<footer className="home-footer">竖排阅读 · 注音 · PDF / EPUB 下载</footer></div></main>;}
