import {zipSync,strToU8} from 'fflate';
import {exportBlocks,blockXHTML,xml,type BookExport} from './export-model';
export async function createEPUB(book:BookExport,progress:(s:string)=>void=()=>{},signal?:AbortSignal){
 progress('正在生成 EPUB…');signal?.throwIfAborted();
 const blocks=exportBlocks(book.html);const parts:{title:string;body:string}[]=[];let body='';let count=0;let title='本文';
 for(const block of blocks){if((block.heading&&body)||count>24000){parts.push({title,body});body='';count=0;}if(block.heading)title=block.runs.map(r=>r.text).join('')||'本文';body+=blockXHTML(block);count+=block.runs.reduce((n,r)=>n+r.text.length,0);}
 if(body)parts.push({title,body});if(!parts.length)throw Error('没有可导出的正文。');
 const document=(title:string,body:string)=>'<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="ja" lang="ja"><head><title>'+xml(title)+'</title><link rel="stylesheet" type="text/css" href="style.css"/></head><body>'+body+'</body></html>';
 const files:Parameters<typeof zipSync>[0]={mimetype:[strToU8('application/epub+zip'),{level:0}]};
 files['META-INF/container.xml']=strToU8('<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>');
 const stamp=new Date().toISOString().replace(/\.\d+Z$/,'Z');const id='urn:uuid:'+crypto.randomUUID();
 files['OEBPS/style.css']=strToU8('html{writing-mode:vertical-rl;-epub-writing-mode:vertical-rl;}body{font-family:"Noto Serif JP","Yu Mincho",serif;line-height:1.9;text-orientation:mixed;line-break:strict;overflow-wrap:break-word;margin:1em;}p{margin:0 0 0 1em;}h1,h2{font-weight:normal;break-after:avoid;}ruby{ruby-position:over;}rt{font-size:0.5em;}nav{writing-mode:horizontal-tb;-epub-writing-mode:horizontal-tb;}a{color:inherit;}');
 files['OEBPS/title.xhtml']=strToU8(document(book.title,'<h1>'+xml(book.title)+'</h1><p>'+xml(book.author)+'</p><p>原文：<a href="'+xml(book.url)+'">'+xml(book.url)+'</a></p>'));
 for(let i=0;i<parts.length;i++){signal?.throwIfAborted();files['OEBPS/part'+i+'.xhtml']=strToU8(document(parts[i].title,parts[i].body));if(i%20===0)await new Promise(r=>setTimeout(r,0));}
 const nav='<nav epub:type="toc" id="toc"><h1>目次</h1><ol><li><a href="title.xhtml">'+xml(book.title)+'</a></li>'+parts.map((p,i)=>'<li><a href="part'+i+'.xhtml">'+xml(p.title)+'</a></li>').join('')+'</ol></nav>';
 files['OEBPS/nav.xhtml']=strToU8(document('目次',nav));
 files['OEBPS/toc.ncx']=strToU8('<?xml version="1.0"?><ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1"><head><meta name="dtb:uid" content="'+id+'"/></head><docTitle><text>'+xml(book.title)+'</text></docTitle><navMap>'+parts.map((p,i)=>'<navPoint id="n'+i+'" playOrder="'+(i+1)+'"><navLabel><text>'+xml(p.title)+'</text></navLabel><content src="part'+i+'.xhtml"/></navPoint>').join('')+'</navMap></ncx>');
 files['OEBPS/package.opf']=strToU8('<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" prefix="rendition: http://www.idpf.org/vocab/rendition/#"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">'+id+'</dc:identifier><dc:title>'+xml(book.title)+'</dc:title><dc:creator>'+xml(book.author||'著者不明')+'</dc:creator><dc:language>ja</dc:language><dc:source>'+xml(book.url)+'</dc:source><meta property="dcterms:modified">'+stamp+'</meta><meta property="rendition:layout">reflowable</meta></metadata><manifest><item id="style" href="style.css" media-type="text/css"/><item id="title" href="title.xhtml" media-type="application/xhtml+xml"/><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>'+parts.map((_,i)=>'<item id="p'+i+'" href="part'+i+'.xhtml" media-type="application/xhtml+xml"/>').join('')+'</manifest><spine page-progression-direction="rtl" toc="ncx"><itemref idref="title"/>'+parts.map((_,i)=>'<itemref idref="p'+i+'"/>').join('')+'</spine></package>');
 signal?.throwIfAborted();progress('正在打包 EPUB…');await new Promise(r=>setTimeout(r,0));return zipSync(files,{level:6});
}
